package com.rminfo.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listProto.proto

public final class ListProto {
  private ListProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FatherOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Father)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Son sons = 1;</code>
     */
    java.util.List<Son>
        getSonsList();
    /**
     * <code>repeated .Son sons = 1;</code>
     */
    Son getSons(int index);
    /**
     * <code>repeated .Son sons = 1;</code>
     */
    int getSonsCount();
    /**
     * <code>repeated .Son sons = 1;</code>
     */
    java.util.List<? extends SonOrBuilder>
        getSonsOrBuilderList();
    /**
     * <code>repeated .Son sons = 1;</code>
     */
    SonOrBuilder getSonsOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code Father}
   */
  public  static final class Father extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Father)
      FatherOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Father.newBuilder() to construct.
    private Father(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Father() {
      sons_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Father(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                sons_ = new java.util.ArrayList<Son>();
                mutable_bitField0_ |= 0x00000001;
              }
              sons_.add(
                  input.readMessage(Son.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          sons_ = java.util.Collections.unmodifiableList(sons_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ListProto.internal_static_Father_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ListProto.internal_static_Father_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Father.class, Builder.class);
    }

    public static final int SONS_FIELD_NUMBER = 1;
    private java.util.List<Son> sons_;
    /**
     * <code>repeated .Son sons = 1;</code>
     */
    public java.util.List<Son> getSonsList() {
      return sons_;
    }
    /**
     * <code>repeated .Son sons = 1;</code>
     */
    public java.util.List<? extends SonOrBuilder>
        getSonsOrBuilderList() {
      return sons_;
    }
    /**
     * <code>repeated .Son sons = 1;</code>
     */
    public int getSonsCount() {
      return sons_.size();
    }
    /**
     * <code>repeated .Son sons = 1;</code>
     */
    public Son getSons(int index) {
      return sons_.get(index);
    }
    /**
     * <code>repeated .Son sons = 1;</code>
     */
    public SonOrBuilder getSonsOrBuilder(
        int index) {
      return sons_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < sons_.size(); i++) {
        output.writeMessage(1, sons_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < sons_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sons_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Father)) {
        return super.equals(obj);
      }
      Father other = (Father) obj;

      boolean result = true;
      result = result && getSonsList()
          .equals(other.getSonsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getSonsCount() > 0) {
        hash = (37 * hash) + SONS_FIELD_NUMBER;
        hash = (53 * hash) + getSonsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Father parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Father parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Father parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Father parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Father parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Father parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Father parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Father parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Father parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Father parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Father parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Father parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Father prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Father}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Father)
        FatherOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ListProto.internal_static_Father_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ListProto.internal_static_Father_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Father.class, Builder.class);
      }

      // Construct using ListProto.Father.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSonsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (sonsBuilder_ == null) {
          sons_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          sonsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ListProto.internal_static_Father_descriptor;
      }

      public Father getDefaultInstanceForType() {
        return Father.getDefaultInstance();
      }

      public Father build() {
        Father result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Father buildPartial() {
        Father result = new Father(this);
        int from_bitField0_ = bitField0_;
        if (sonsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            sons_ = java.util.Collections.unmodifiableList(sons_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.sons_ = sons_;
        } else {
          result.sons_ = sonsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Father) {
          return mergeFrom((Father)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Father other) {
        if (other == Father.getDefaultInstance()) return this;
        if (sonsBuilder_ == null) {
          if (!other.sons_.isEmpty()) {
            if (sons_.isEmpty()) {
              sons_ = other.sons_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSonsIsMutable();
              sons_.addAll(other.sons_);
            }
            onChanged();
          }
        } else {
          if (!other.sons_.isEmpty()) {
            if (sonsBuilder_.isEmpty()) {
              sonsBuilder_.dispose();
              sonsBuilder_ = null;
              sons_ = other.sons_;
              bitField0_ = (bitField0_ & ~0x00000001);
              sonsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSonsFieldBuilder() : null;
            } else {
              sonsBuilder_.addAllMessages(other.sons_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Father parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Father) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Son> sons_ =
        java.util.Collections.emptyList();
      private void ensureSonsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          sons_ = new java.util.ArrayList<Son>(sons_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Son, Son.Builder, SonOrBuilder> sonsBuilder_;

      /**
       * <code>repeated .Son sons = 1;</code>
       */
      public java.util.List<Son> getSonsList() {
        if (sonsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sons_);
        } else {
          return sonsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Son sons = 1;</code>
       */
      public int getSonsCount() {
        if (sonsBuilder_ == null) {
          return sons_.size();
        } else {
          return sonsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Son sons = 1;</code>
       */
      public Son getSons(int index) {
        if (sonsBuilder_ == null) {
          return sons_.get(index);
        } else {
          return sonsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Son sons = 1;</code>
       */
      public Builder setSons(
          int index, Son value) {
        if (sonsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSonsIsMutable();
          sons_.set(index, value);
          onChanged();
        } else {
          sonsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Son sons = 1;</code>
       */
      public Builder setSons(
          int index, Son.Builder builderForValue) {
        if (sonsBuilder_ == null) {
          ensureSonsIsMutable();
          sons_.set(index, builderForValue.build());
          onChanged();
        } else {
          sonsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Son sons = 1;</code>
       */
      public Builder addSons(Son value) {
        if (sonsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSonsIsMutable();
          sons_.add(value);
          onChanged();
        } else {
          sonsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Son sons = 1;</code>
       */
      public Builder addSons(
          int index, Son value) {
        if (sonsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSonsIsMutable();
          sons_.add(index, value);
          onChanged();
        } else {
          sonsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Son sons = 1;</code>
       */
      public Builder addSons(
          Son.Builder builderForValue) {
        if (sonsBuilder_ == null) {
          ensureSonsIsMutable();
          sons_.add(builderForValue.build());
          onChanged();
        } else {
          sonsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Son sons = 1;</code>
       */
      public Builder addSons(
          int index, Son.Builder builderForValue) {
        if (sonsBuilder_ == null) {
          ensureSonsIsMutable();
          sons_.add(index, builderForValue.build());
          onChanged();
        } else {
          sonsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Son sons = 1;</code>
       */
      public Builder addAllSons(
          Iterable<? extends Son> values) {
        if (sonsBuilder_ == null) {
          ensureSonsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, sons_);
          onChanged();
        } else {
          sonsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Son sons = 1;</code>
       */
      public Builder clearSons() {
        if (sonsBuilder_ == null) {
          sons_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          sonsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Son sons = 1;</code>
       */
      public Builder removeSons(int index) {
        if (sonsBuilder_ == null) {
          ensureSonsIsMutable();
          sons_.remove(index);
          onChanged();
        } else {
          sonsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Son sons = 1;</code>
       */
      public Son.Builder getSonsBuilder(
          int index) {
        return getSonsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Son sons = 1;</code>
       */
      public SonOrBuilder getSonsOrBuilder(
          int index) {
        if (sonsBuilder_ == null) {
          return sons_.get(index);  } else {
          return sonsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Son sons = 1;</code>
       */
      public java.util.List<? extends SonOrBuilder>
           getSonsOrBuilderList() {
        if (sonsBuilder_ != null) {
          return sonsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sons_);
        }
      }
      /**
       * <code>repeated .Son sons = 1;</code>
       */
      public Son.Builder addSonsBuilder() {
        return getSonsFieldBuilder().addBuilder(
            Son.getDefaultInstance());
      }
      /**
       * <code>repeated .Son sons = 1;</code>
       */
      public Son.Builder addSonsBuilder(
          int index) {
        return getSonsFieldBuilder().addBuilder(
            index, Son.getDefaultInstance());
      }
      /**
       * <code>repeated .Son sons = 1;</code>
       */
      public java.util.List<Son.Builder>
           getSonsBuilderList() {
        return getSonsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Son, Son.Builder, SonOrBuilder>
          getSonsFieldBuilder() {
        if (sonsBuilder_ == null) {
          sonsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Son, Son.Builder, SonOrBuilder>(
                  sons_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          sons_ = null;
        }
        return sonsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Father)
    }

    // @@protoc_insertion_point(class_scope:Father)
    private static final Father DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Father();
    }

    public static Father getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Father>
        PARSER = new com.google.protobuf.AbstractParser<Father>() {
      public Father parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Father(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Father> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Father> getParserForType() {
      return PARSER;
    }

    public Father getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Son)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 2;</code>
     */
    String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code Son}
   */
  public  static final class Son extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Son)
      SonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Son.newBuilder() to construct.
    private Son(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Son() {
      name_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Son(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ListProto.internal_static_Son_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ListProto.internal_static_Son_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Son.class, Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Son)) {
        return super.equals(obj);
      }
      Son other = (Son) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Son parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Son parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Son parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Son parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Son parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Son parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Son parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Son parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Son parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Son parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Son parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Son parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Son prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Son}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Son)
        SonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ListProto.internal_static_Son_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ListProto.internal_static_Son_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Son.class, Builder.class);
      }

      // Construct using ListProto.Son.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ListProto.internal_static_Son_descriptor;
      }

      public Son getDefaultInstanceForType() {
        return Son.getDefaultInstance();
      }

      public Son build() {
        Son result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Son buildPartial() {
        Son result = new Son(this);
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Son) {
          return mergeFrom((Son)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Son other) {
        if (other == Son.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Son parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Son) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Son)
    }

    // @@protoc_insertion_point(class_scope:Son)
    private static final Son DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Son();
    }

    public static Son getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Son>
        PARSER = new com.google.protobuf.AbstractParser<Son>() {
      public Son parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Son(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Son> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Son> getParserForType() {
      return PARSER;
    }

    public Son getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Father_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Father_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Son_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Son_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017listProto.proto\"\034\n\006Father\022\022\n\004sons\030\001 \003(" +
      "\0132\004.Son\"\023\n\003Son\022\014\n\004name\030\002 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Father_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Father_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Father_descriptor,
        new String[] { "Sons", });
    internal_static_Son_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Son_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Son_descriptor,
        new String[] { "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
