package com.rminfo.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testProto.proto

public final class TestProto {
  private TestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *参数类型 参数名称=字段编码值  
     * </pre>
     *
     * <code>int32 senderId = 1;</code>
     */
    int getSenderId();

    /**
     * <pre>
     * 接受人ID  
     * </pre>
     *
     * <code>int32 receiverId = 2;</code>
     */
    int getReceiverId();

    /**
     * <pre>
     * 发送人姓名  
     * </pre>
     *
     * <code>string senderName = 3;</code>
     */
    String getSenderName();
    /**
     * <pre>
     * 发送人姓名  
     * </pre>
     *
     * <code>string senderName = 3;</code>
     */
    com.google.protobuf.ByteString
        getSenderNameBytes();

    /**
     * <pre>
     * 接收人姓名  
     * </pre>
     *
     * <code>string receiverName = 4;</code>
     */
    String getReceiverName();
    /**
     * <pre>
     * 接收人姓名  
     * </pre>
     *
     * <code>string receiverName = 4;</code>
     */
    com.google.protobuf.ByteString
        getReceiverNameBytes();

    /**
     * <pre>
     * 发送人头像URL  
     * </pre>
     *
     * <code>string senderHeadPortrait = 5;</code>
     */
    String getSenderHeadPortrait();
    /**
     * <pre>
     * 发送人头像URL  
     * </pre>
     *
     * <code>string senderHeadPortrait = 5;</code>
     */
    com.google.protobuf.ByteString
        getSenderHeadPortraitBytes();
  }
  /**
   * <pre>
   *message是固定的。UserInfo是类名，可以随意指定，符合规范即可  
   * </pre>
   *
   * Protobuf type {@code UserInfo}
   */
  public  static final class UserInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UserInfo)
      UserInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserInfo.newBuilder() to construct.
    private UserInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserInfo() {
      senderId_ = 0;
      receiverId_ = 0;
      senderName_ = "";
      receiverName_ = "";
      senderHeadPortrait_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              senderId_ = input.readInt32();
              break;
            }
            case 16: {

              receiverId_ = input.readInt32();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              senderName_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              receiverName_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              senderHeadPortrait_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TestProto.internal_static_UserInfo_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TestProto.internal_static_UserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserInfo.class, Builder.class);
    }

    public static final int SENDERID_FIELD_NUMBER = 1;
    private int senderId_;
    /**
     * <pre>
     *参数类型 参数名称=字段编码值  
     * </pre>
     *
     * <code>int32 senderId = 1;</code>
     */
    public int getSenderId() {
      return senderId_;
    }

    public static final int RECEIVERID_FIELD_NUMBER = 2;
    private int receiverId_;
    /**
     * <pre>
     * 接受人ID  
     * </pre>
     *
     * <code>int32 receiverId = 2;</code>
     */
    public int getReceiverId() {
      return receiverId_;
    }

    public static final int SENDERNAME_FIELD_NUMBER = 3;
    private volatile Object senderName_;
    /**
     * <pre>
     * 发送人姓名  
     * </pre>
     *
     * <code>string senderName = 3;</code>
     */
    public String getSenderName() {
      Object ref = senderName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        senderName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 发送人姓名  
     * </pre>
     *
     * <code>string senderName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSenderNameBytes() {
      Object ref = senderName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        senderName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVERNAME_FIELD_NUMBER = 4;
    private volatile Object receiverName_;
    /**
     * <pre>
     * 接收人姓名  
     * </pre>
     *
     * <code>string receiverName = 4;</code>
     */
    public String getReceiverName() {
      Object ref = receiverName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        receiverName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 接收人姓名  
     * </pre>
     *
     * <code>string receiverName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverNameBytes() {
      Object ref = receiverName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        receiverName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERHEADPORTRAIT_FIELD_NUMBER = 5;
    private volatile Object senderHeadPortrait_;
    /**
     * <pre>
     * 发送人头像URL  
     * </pre>
     *
     * <code>string senderHeadPortrait = 5;</code>
     */
    public String getSenderHeadPortrait() {
      Object ref = senderHeadPortrait_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        senderHeadPortrait_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 发送人头像URL  
     * </pre>
     *
     * <code>string senderHeadPortrait = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSenderHeadPortraitBytes() {
      Object ref = senderHeadPortrait_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        senderHeadPortrait_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (senderId_ != 0) {
        output.writeInt32(1, senderId_);
      }
      if (receiverId_ != 0) {
        output.writeInt32(2, receiverId_);
      }
      if (!getSenderNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, senderName_);
      }
      if (!getReceiverNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, receiverName_);
      }
      if (!getSenderHeadPortraitBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, senderHeadPortrait_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (senderId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, senderId_);
      }
      if (receiverId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, receiverId_);
      }
      if (!getSenderNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, senderName_);
      }
      if (!getReceiverNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, receiverName_);
      }
      if (!getSenderHeadPortraitBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, senderHeadPortrait_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UserInfo)) {
        return super.equals(obj);
      }
      UserInfo other = (UserInfo) obj;

      boolean result = true;
      result = result && (getSenderId()
          == other.getSenderId());
      result = result && (getReceiverId()
          == other.getReceiverId());
      result = result && getSenderName()
          .equals(other.getSenderName());
      result = result && getReceiverName()
          .equals(other.getReceiverName());
      result = result && getSenderHeadPortrait()
          .equals(other.getSenderHeadPortrait());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENDERID_FIELD_NUMBER;
      hash = (53 * hash) + getSenderId();
      hash = (37 * hash) + RECEIVERID_FIELD_NUMBER;
      hash = (53 * hash) + getReceiverId();
      hash = (37 * hash) + SENDERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSenderName().hashCode();
      hash = (37 * hash) + RECEIVERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getReceiverName().hashCode();
      hash = (37 * hash) + SENDERHEADPORTRAIT_FIELD_NUMBER;
      hash = (53 * hash) + getSenderHeadPortrait().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UserInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *message是固定的。UserInfo是类名，可以随意指定，符合规范即可  
     * </pre>
     *
     * Protobuf type {@code UserInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserInfo)
        UserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TestProto.internal_static_UserInfo_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TestProto.internal_static_UserInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UserInfo.class, Builder.class);
      }

      // Construct using TestProto.UserInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        senderId_ = 0;

        receiverId_ = 0;

        senderName_ = "";

        receiverName_ = "";

        senderHeadPortrait_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TestProto.internal_static_UserInfo_descriptor;
      }

      public UserInfo getDefaultInstanceForType() {
        return UserInfo.getDefaultInstance();
      }

      public UserInfo build() {
        UserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public UserInfo buildPartial() {
        UserInfo result = new UserInfo(this);
        result.senderId_ = senderId_;
        result.receiverId_ = receiverId_;
        result.senderName_ = senderName_;
        result.receiverName_ = receiverName_;
        result.senderHeadPortrait_ = senderHeadPortrait_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserInfo) {
          return mergeFrom((UserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserInfo other) {
        if (other == UserInfo.getDefaultInstance()) return this;
        if (other.getSenderId() != 0) {
          setSenderId(other.getSenderId());
        }
        if (other.getReceiverId() != 0) {
          setReceiverId(other.getReceiverId());
        }
        if (!other.getSenderName().isEmpty()) {
          senderName_ = other.senderName_;
          onChanged();
        }
        if (!other.getReceiverName().isEmpty()) {
          receiverName_ = other.receiverName_;
          onChanged();
        }
        if (!other.getSenderHeadPortrait().isEmpty()) {
          senderHeadPortrait_ = other.senderHeadPortrait_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UserInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UserInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int senderId_ ;
      /**
       * <pre>
       *参数类型 参数名称=字段编码值  
       * </pre>
       *
       * <code>int32 senderId = 1;</code>
       */
      public int getSenderId() {
        return senderId_;
      }
      /**
       * <pre>
       *参数类型 参数名称=字段编码值  
       * </pre>
       *
       * <code>int32 senderId = 1;</code>
       */
      public Builder setSenderId(int value) {
        
        senderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *参数类型 参数名称=字段编码值  
       * </pre>
       *
       * <code>int32 senderId = 1;</code>
       */
      public Builder clearSenderId() {
        
        senderId_ = 0;
        onChanged();
        return this;
      }

      private int receiverId_ ;
      /**
       * <pre>
       * 接受人ID  
       * </pre>
       *
       * <code>int32 receiverId = 2;</code>
       */
      public int getReceiverId() {
        return receiverId_;
      }
      /**
       * <pre>
       * 接受人ID  
       * </pre>
       *
       * <code>int32 receiverId = 2;</code>
       */
      public Builder setReceiverId(int value) {
        
        receiverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 接受人ID  
       * </pre>
       *
       * <code>int32 receiverId = 2;</code>
       */
      public Builder clearReceiverId() {
        
        receiverId_ = 0;
        onChanged();
        return this;
      }

      private Object senderName_ = "";
      /**
       * <pre>
       * 发送人姓名  
       * </pre>
       *
       * <code>string senderName = 3;</code>
       */
      public String getSenderName() {
        Object ref = senderName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          senderName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 发送人姓名  
       * </pre>
       *
       * <code>string senderName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSenderNameBytes() {
        Object ref = senderName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          senderName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 发送人姓名  
       * </pre>
       *
       * <code>string senderName = 3;</code>
       */
      public Builder setSenderName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送人姓名  
       * </pre>
       *
       * <code>string senderName = 3;</code>
       */
      public Builder clearSenderName() {
        
        senderName_ = getDefaultInstance().getSenderName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送人姓名  
       * </pre>
       *
       * <code>string senderName = 3;</code>
       */
      public Builder setSenderNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderName_ = value;
        onChanged();
        return this;
      }

      private Object receiverName_ = "";
      /**
       * <pre>
       * 接收人姓名  
       * </pre>
       *
       * <code>string receiverName = 4;</code>
       */
      public String getReceiverName() {
        Object ref = receiverName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          receiverName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 接收人姓名  
       * </pre>
       *
       * <code>string receiverName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverNameBytes() {
        Object ref = receiverName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          receiverName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 接收人姓名  
       * </pre>
       *
       * <code>string receiverName = 4;</code>
       */
      public Builder setReceiverName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiverName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 接收人姓名  
       * </pre>
       *
       * <code>string receiverName = 4;</code>
       */
      public Builder clearReceiverName() {
        
        receiverName_ = getDefaultInstance().getReceiverName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 接收人姓名  
       * </pre>
       *
       * <code>string receiverName = 4;</code>
       */
      public Builder setReceiverNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiverName_ = value;
        onChanged();
        return this;
      }

      private Object senderHeadPortrait_ = "";
      /**
       * <pre>
       * 发送人头像URL  
       * </pre>
       *
       * <code>string senderHeadPortrait = 5;</code>
       */
      public String getSenderHeadPortrait() {
        Object ref = senderHeadPortrait_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          senderHeadPortrait_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 发送人头像URL  
       * </pre>
       *
       * <code>string senderHeadPortrait = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSenderHeadPortraitBytes() {
        Object ref = senderHeadPortrait_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          senderHeadPortrait_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 发送人头像URL  
       * </pre>
       *
       * <code>string senderHeadPortrait = 5;</code>
       */
      public Builder setSenderHeadPortrait(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderHeadPortrait_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送人头像URL  
       * </pre>
       *
       * <code>string senderHeadPortrait = 5;</code>
       */
      public Builder clearSenderHeadPortrait() {
        
        senderHeadPortrait_ = getDefaultInstance().getSenderHeadPortrait();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送人头像URL  
       * </pre>
       *
       * <code>string senderHeadPortrait = 5;</code>
       */
      public Builder setSenderHeadPortraitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderHeadPortrait_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UserInfo)
    }

    // @@protoc_insertion_point(class_scope:UserInfo)
    private static final UserInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserInfo();
    }

    public static UserInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserInfo>
        PARSER = new com.google.protobuf.AbstractParser<UserInfo>() {
      public UserInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<UserInfo> getParserForType() {
      return PARSER;
    }

    public UserInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017testProto.proto\"v\n\010UserInfo\022\020\n\010senderI" +
      "d\030\001 \001(\005\022\022\n\nreceiverId\030\002 \001(\005\022\022\n\nsenderNam" +
      "e\030\003 \001(\t\022\024\n\014receiverName\030\004 \001(\t\022\032\n\022senderH" +
      "eadPortrait\030\005 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_UserInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserInfo_descriptor,
        new String[] { "SenderId", "ReceiverId", "SenderName", "ReceiverName", "SenderHeadPortrait", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
